server:
  port: 8300
  servlet:
    context-path: /board-service

spring:
  application:
    name: board-service

---
spring:
  config:
    import: "optional:configserver:http://127.0.0.1:8888"
    use-legacy-processing: true #unable to load config data~ 오류 발생시 사용
  cloud:
    config:
      fail-fast: true #클라이언트 서버를 시작할 때 Config 서버에서 정보를 로드할 수 없을 경우에는 서버를 실행하지 않겠다는 설정
      name: msaConfigFile

---
# actuator를 이용하여 서버 재시작 없이 변경내용 반영 가능하게 함.
management:
  endpoints:
    web:
      exposure:
        include: refresh

kafka:
  consumer:
    group-id: first-group
  bootstrap-servers: 127.0.0.1:9092